### ISSUE TITLE
Why did you remove the executable for the latest version from releases?

### ISSUE THREAD

**Issue by Avnsx** [geekuillaume/soundsync#154]
Can't download the compiled version anymore

**Comment by geekuillaume** [comment]
The windows executable doesn't build anymore because of an unknown bug on Github CI. The macOS executable doesn't build anymore because the Apple license I paid is expired and I don't want to spend $100 on a new one. I don't have time to maintain this project anymore and cannot support building these new executable anymore.

**Comment by Avnsx** [comment]
> I don't have time to maintain this project anymore and cannot support building these new executable anymore.

Then turn it into a public archive
