### ISSUE TITLE
Windows Audio

### ISSUE THREAD

**Issue by LostSoulfly** [geekuillaume/soundsync#33]
The main website says:
`On Windows and Linux, Soundsync capture the sound emitted from your computer in any program`

but I'm only able to use line-in audio/microphones. How do I use a different Windows audio source?

I just downloaded the newest version from the website.

![image](https://user-images.githubusercontent.com/9120519/94302924-05949b80-ff3b-11ea-89d3-7ae6ada40c5d.png)

also, every time I refresh the local page I get this:
![image](https://user-images.githubusercontent.com/9120519/94303069-412f6580-ff3b-11ea-8dbe-78acdfca668a.png)

... and then have to remove "/controller" from the url to get it to connect again.

**Comment by geekuillaume** [comment]
I've activated the loopback feature on the last version of Soundsync (v0.4.0). It was disabled previously because of bugs and I forgot to update the Readme. This new version will show every Windows audio output as a audio source in the webui. I've also fixed the refresh bug.

As everything should be good with the last version I'm closing this issue. Feel free to reopen it if you still have these problems.
